export const METRICS_HTTP_TIMEOUT_MS = 5_000;
export const METRICS_RUNTIME_SUMMARY_INTERVAL_MS = 30_000;
export const METRICS_COLLECT_INTERVAL_MS = 5_000;
export const METRICS_LIFETIME_UPTIME_INCREMENT_SECONDS = 5;
